version: "3.8"
services:
  delve-into-docker:
    container_name: delve-into-docker
    build:
      context: .
    command: "dlv debug github.com/kaperys/delve-into-docker-app --listen=:40000 --headless=true --api-version=2 --log"
    security_opt:
      - 'seccomp:unconfined'
    ports:
    - 40000:40000
    - 1541:1541
